defaultProject: "trim-icon-498815-a0"
defaultLocation: "US"
defaultDataset: "readmission"
defaultAssertionDataset: "readmission_assertions"
vars:
  mimic_database: "trim-icon-498815-a0"
  mimic_hosp_schema: "mimiciv_3_1_hosp"
  mimic_icu_schema: "mimiciv_3_1_icu"
  mimic_ed_schema: "mimiciv_ed"
